model_path: null
in_channels: 3
down_sampling_factor: 4
down_sampling_channels: 32
spatial_dropout_p: 0.1
channels_per_group: 64
n_groups: 8
dilation_rates:
- 1
- 2
- 4
- 8
- 16
steps: 10
margin: 1
lr: 0.001
